### ISSUE TITLE
Bug Report on Disappeared Modded Campaign Saves

### ISSUE THREAD

**Issue by nizhuan-jjr** [Acenm5/GHEM#2]
Game Version 1.1.8323.0
I believe it's the game bug that caused such problem.
All modded campaign saves will disappear after a game restart.
There's my video that clearly shows what happened：
https://streamable.com/q2lcqg
（GoogleDrive）https://drive.google.com/file/d/18dfYWcA5H2wqbX-aqCO551baP7R2NoX0/view?usp=sharing

**Comment by nizhuan-jjr** [comment]
Oops, I thought this is a GH official repo...
EDIT: After installing GHEM, a new modded campaign save no longer disappears after a game restart. Nice!

**Comment by Acenm5** [comment]
Glad to see the mod still fixes that issue!
